@BaseUri = http://127.0.0.1:8000/api 
@Controller = factures
@id = 9

###
GET {{BaseUri}}/{{Controller}}

###
GET {{BaseUri}}/{{Controller}}/{{id}}


###
POST {{BaseUri}}/{{Controller}}
Content-Type: application/json

{
    "facture_id": 0,
    "reglement" : {
        "condition_id" : 3, 
        "mode_id" : 1, 
        "interet_id": 3
    }
}

### 
DELETE  {{BaseUri}}/{{Controller}}/{{id}}
