@BaseUri = http://127.0.0.1:8000/api 

@Controller = factures

@id = 4


###
GET {{BaseUri}}/{{Controller}}

###
GET {{BaseUri}}/{{Controller}}/{{id}}

###
POST {{BaseUri}}/{{Controller}}
Content-Type: application/json

{
    "user_id" : 1, 
    "client_id" : null , 
    "societe_id" : 1,
    "status_id" : 1,
    "reglement" : {
        "condition_id" : 3, 
        "mode_id" : 1, 
        "interet_id" : 3, 
        "compte_bancaire" : null
    }, 
    "articles": [
        {
        "type_id" : 1, 
        "quantité" : 2 ,
        "prix_ht" : 39 , 
        "tva" : 20, 
        "reduction"  : 0 , 
        "total_ht"  : 78 , 
        "total_ttc" : 93 , 
        "description": "ddd"
        }, 
        {
            "type_id" : 1, 
            "quantité" : 2 ,
            "prix_ht" : 39 , 
            "tva" : 20, 
            "reduction"  : 0 , 
            "total_ht"  : 78 , 
            "total_ttc" : 93 , 
            "description": "ddd"
        }
    ], 
    "textDocument" : {
        "introduction" : "intro", 
        "conclusion" : "conclusion", 
        "pied_page" : "footer", 
        "condition" : null
    }, 
    "motCles" : [
        {
            "mot_de_value": "LLL"
        },
        {    
            "mot_de_value": "LLL"
        },
        {
            "mot_de_value": "LLL"
        },
        {
            "mot_de_value": "LLL"
        }
    
    ] 
}

### 
DELETE  {{BaseUri}}/{{Controller}}/{{id}}
